const data = {
  total: 7.0,
  items: [
    {
      code: 'PDQOWRSM4644',
      nick: 'maru-bamboo-toothbrush-standard-1ea',
      type: 'EXTRA',
      brand: null,
      title: '마루 대나무 칫솔 스탠다드(1개입)',
      subTitle: null,
      price: 2800.0,
      listPrice: null,
      count: null,
      applyCount: null,
      surveyId: null,
      checkState: null,
      imageUrl: null,
      conceptUrl: null,
      bottleUrl: null,
      color: '#cccccc',
      summary: null,
      content: null,
      volume: null,
      intake: null,
      shape: null,
      slogan: null,
      description: null,
      ingredients: null,
      caution: null,
      iconText: null,
      limitation: null,
      saleState: 1.0,
      onetimeState: null,
      subscriberState: null,
      eventState: null,
      soldoutState: null,
      takebackCount: null,
      ord: null,
      maxPurchaseLimit: 5.0,
      discount: null,
      hashtag: null,
      seoTitle: null,
      seoKeywords: null,
      surveySummary: null,
      medicineNo: '202210270056',
      medicineTitle: null,
      medicineImageUrl: null,
      distributionTitle: null,
      tags: null,
      contains: null,
      marks: null,
      // topCategoryCode: 'health_supplies',
      //  topCategoryTitle: '건강용품',
      // brandInfo: {
      //   nickname: 'drnoah',
      //   title: '닥터노아',
      //   slogan:
      //     '매일 쓰는 칫솔과 치약에서 영원히 썩지 않는 것들을 덜어내고, 자연에서 얻은 재료와 성분을 더해 우리 몸에 안전하고 건강한 오랄 케어 제품을 만듭니다. 닥터노아 제품은 자연을 닮아 아름답고, 자연의 솜씨를 익혀 제 기능을 하기에도 충분합니다.',
      //   logoUrl:
      //     'https://pillykr.s3.ap-northeast-2.amazonaws.com/store/brand/drnoah/logo.png',
      //   coverUrl:
      //     'https://pillykr.s3.ap-northeast-2.amazonaws.com/store/brand/drnoah/brand.jpg',
      //   modTsp: '2022-11-01 02:50:25',
      //   regTsp: '2022-11-01 02:50:25',
      // },
      certs: null,
      faqs: null,
      noticeInfo: null,
      thumbnailImages: [
        {
          type: 'THUMBNAIL',
          ord: 1.0,
          //   url: 'https://img.pilly.kr/product/store/PDQOWRSM4644/product_01.png',
          modTsp: '2022-11-01 02:51:12',
          regTsp: '2022-11-01 02:51:12',
        },
        {
          type: 'THUMBNAIL',
          ord: 2.0,
          url: 'https://img.pilly.kr/product/store/PDQOWRSM4644/product_02.jpg',
          modTsp: '2022-11-01 02:51:12',
          regTsp: '2022-11-01 02:51:12',
        },
        {
          type: 'THUMBNAIL',
          ord: 3.0,
          url: 'https://img.pilly.kr/product/store/PDQOWRSM4644/product_03.jpg',
          modTsp: '2022-11-01 02:51:12',
          regTsp: '2022-11-01 02:51:12',
        },
        {
          type: 'THUMBNAIL',
          ord: 4.0,
          url: 'https://img.pilly.kr/product/store/PDQOWRSM4644/product_04.jpg',
          modTsp: '2022-11-01 02:51:12',
          regTsp: '2022-11-01 02:51:12',
        },
      ],
      detailImages: null,
      reviewRating: 0.0,
      reviewCount: 0.0,
      reviewStats: null,
      modTsp: '2022-10-19 21:30:47',
      regTsp: '2022-10-19 21:30:47',
    },
    {
      code: 'PDQSTPRO9693',
      nick: 'maru-bamboo-toothbrush-standard-6ea',
      type: 'EXTRA',
      brand: null,
      title: '마루 대나무 칫솔 스탠다드(6개입)',
      subTitle: null,
      price: 15960.0,
      listPrice: 16800.0,
      count: null,
      applyCount: null,
      surveyId: null,
      checkState: null,
      imageUrl: null,
      conceptUrl: null,
      bottleUrl: null,
      color: '#cccccc',
      summary: null,
      content: null,
      volume: null,
      intake: null,
      shape: null,
      slogan: null,
      description: null,
      ingredients: null,
      caution: null,
      iconText: null,
      limitation: null,
      saleState: 1.0,
      onetimeState: null,
      subscriberState: null,
      eventState: null,
      soldoutState: null,
      takebackCount: null,
      ord: null,
      maxPurchaseLimit: 5.0,
      discount: '5%',
      hashtag: null,
      seoTitle: null,
      seoKeywords: null,
      surveySummary: null,
      medicineNo: '202210270057',
      medicineTitle: null,
      medicineImageUrl: null,
      distributionTitle: null,
      tags: null,
      contains: null,
      marks: null,
      topCategoryCode: 'health_supplies',
      topCategoryTitle: '건강용품',
      brandInfo: {
        nickname: 'drnoah',
        title: '닥터노아',
        slogan:
          '매일 쓰는 칫솔과 치약에서 영원히 썩지 않는 것들을 덜어내고, 자연에서 얻은 재료와 성분을 더해 우리 몸에 안전하고 건강한 오랄 케어 제품을 만듭니다. 닥터노아 제품은 자연을 닮아 아름답고, 자연의 솜씨를 익혀 제 기능을 하기에도 충분합니다.',
        logoUrl:
          'https://pillykr.s3.ap-northeast-2.amazonaws.com/store/brand/drnoah/logo.png',
        coverUrl:
          'https://pillykr.s3.ap-northeast-2.amazonaws.com/store/brand/drnoah/brand.jpg',
        modTsp: '2022-11-01 02:50:25',
        regTsp: '2022-11-01 02:50:25',
      },
      certs: null,
      faqs: null,
      noticeInfo: null,
      thumbnailImages: [
        {
          type: 'THUMBNAIL',
          ord: 1.0,
          url: 'https://img.pilly.kr/product/store/PDQSTPRO9693/product_01.png',
          modTsp: '2022-11-01 02:51:12',
          regTsp: '2022-11-01 02:51:12',
        },
        {
          type: 'THUMBNAIL',
          ord: 2.0,
          url: 'https://img.pilly.kr/product/store/PDQSTPRO9693/product_02.jpg',
          modTsp: '2022-11-01 02:51:12',
          regTsp: '2022-11-01 02:51:12',
        },
        {
          type: 'THUMBNAIL',
          ord: 3.0,
          url: 'https://img.pilly.kr/product/store/PDQSTPRO9693/product_03.jpg',
          modTsp: '2022-11-01 02:51:12',
          regTsp: '2022-11-01 02:51:12',
        },
        {
          type: 'THUMBNAIL',
          ord: 4.0,
          url: 'https://img.pilly.kr/product/store/PDQSTPRO9693/product_04.jpg',
          modTsp: '2022-11-01 02:51:12',
          regTsp: '2022-11-01 02:51:12',
        },
        {
          type: 'THUMBNAIL',
          ord: 5.0,
          url: 'https://img.pilly.kr/product/store/PDQSTPRO9693/product_05.jpg',
          modTsp: '2022-11-01 02:51:12',
          regTsp: '2022-11-01 02:51:12',
        },
        {
          type: 'THUMBNAIL',
          ord: 6.0,
          url: 'https://img.pilly.kr/product/store/PDQSTPRO9693/product_06.jpg',
          modTsp: '2022-11-01 02:51:12',
          regTsp: '2022-11-01 02:51:12',
        },
        {
          type: 'THUMBNAIL',
          ord: 7.0,
          url: 'https://img.pilly.kr/product/store/PDQSTPRO9693/product_07.jpg',
          modTsp: '2022-11-01 02:51:12',
          regTsp: '2022-11-01 02:51:12',
        },
      ],
      detailImages: null,
      reviewRating: 0.0,
      reviewCount: 0.0,
      reviewStats: null,
      modTsp: '2022-10-19 21:30:47',
      regTsp: '2022-10-19 21:30:47',
    },
    {
      code: 'PDLCCEPN9793',
      nick: 'drnoah-floss',
      type: 'EXTRA',
      brand: null,
      title: '닥터노아 치실(실크)',
      subTitle: null,
      price: 4640.0,
      listPrice: 5800.0,
      count: null,
      applyCount: null,
      surveyId: null,
      checkState: null,
      imageUrl: null,
      conceptUrl: null,
      bottleUrl: null,
      color: '#cccccc',
      summary: null,
      content: null,
      volume: null,
      intake: null,
      shape: null,
      slogan: null,
      description: null,
      ingredients: null,
      caution: null,
      iconText: null,
      limitation: null,
      saleState: 1.0,
      onetimeState: null,
      subscriberState: null,
      eventState: null,
      soldoutState: null,
      takebackCount: null,
      ord: null,
      maxPurchaseLimit: 5.0,
      discount: '20%',
      hashtag: null,
      seoTitle: null,
      seoKeywords: null,
      surveySummary: null,
      medicineNo: '202210270058',
      medicineTitle: null,
      medicineImageUrl: null,
      distributionTitle: null,
      tags: null,
      contains: null,
      marks: null,
      topCategoryCode: 'health_supplies',
      topCategoryTitle: '건강용품',
      brandInfo: {
        nickname: 'drnoah',
        title: '닥터노아',
        slogan:
          '매일 쓰는 칫솔과 치약에서 영원히 썩지 않는 것들을 덜어내고, 자연에서 얻은 재료와 성분을 더해 우리 몸에 안전하고 건강한 오랄 케어 제품을 만듭니다. 닥터노아 제품은 자연을 닮아 아름답고, 자연의 솜씨를 익혀 제 기능을 하기에도 충분합니다.',
        logoUrl:
          'https://pillykr.s3.ap-northeast-2.amazonaws.com/store/brand/drnoah/logo.png',
        coverUrl:
          'https://pillykr.s3.ap-northeast-2.amazonaws.com/store/brand/drnoah/brand.jpg',
        modTsp: '2022-11-01 02:50:25',
        regTsp: '2022-11-01 02:50:25',
      },
      certs: null,
      faqs: null,
      noticeInfo: null,
      thumbnailImages: [
        {
          type: 'THUMBNAIL',
          ord: 1.0,
          url: 'https://img.pilly.kr/product/store/PDLCCEPN9793/product_01.png',
          modTsp: '2022-11-01 02:51:13',
          regTsp: '2022-11-01 02:51:13',
        },
        {
          type: 'THUMBNAIL',
          ord: 2.0,
          url: 'https://img.pilly.kr/product/store/PDLCCEPN9793/product_02.jpg',
          modTsp: '2022-11-01 02:51:13',
          regTsp: '2022-11-01 02:51:13',
        },
        {
          type: 'THUMBNAIL',
          ord: 3.0,
          url: 'https://img.pilly.kr/product/store/PDLCCEPN9793/product_03.jpg',
          modTsp: '2022-11-01 02:51:13',
          regTsp: '2022-11-01 02:51:13',
        },
      ],
      detailImages: null,
      reviewRating: 0.0,
      reviewCount: 0.0,
      reviewStats: null,
      modTsp: '2022-10-19 21:30:47',
      regTsp: '2022-10-19 21:30:47',
    },
    {
      code: 'PDBUVVOI3999',
      nick: 'o-bits-xylitol-toothpaste-fresh',
      type: 'EXTRA',
      brand: null,
      title: '오비츠 자일리톨 고체치약 프레쉬민트향',
      subTitle: null,
      price: 5300.0,
      listPrice: null,
      count: null,
      applyCount: null,
      surveyId: null,
      checkState: null,
      imageUrl: null,
      conceptUrl: null,
      bottleUrl: null,
      color: '#cccccc',
      summary: null,
      content: null,
      volume: null,
      intake: null,
      shape: null,
      slogan: null,
      description: null,
      ingredients: null,
      caution: null,
      iconText: null,
      limitation: null,
      saleState: 1.0,
      onetimeState: null,
      subscriberState: null,
      eventState: null,
      soldoutState: null,
      takebackCount: null,
      ord: null,
      maxPurchaseLimit: 5.0,
      discount: null,
      hashtag: null,
      seoTitle: null,
      seoKeywords: null,
      surveySummary: null,
      medicineNo: '202210270059',
      medicineTitle: null,
      medicineImageUrl: null,
      distributionTitle: null,
      tags: null,
      contains: null,
      marks: null,
      topCategoryCode: 'health_supplies',
      topCategoryTitle: '건강용품',
      brandInfo: {
        nickname: 'drnoah',
        title: '닥터노아',
        slogan:
          '매일 쓰는 칫솔과 치약에서 영원히 썩지 않는 것들을 덜어내고, 자연에서 얻은 재료와 성분을 더해 우리 몸에 안전하고 건강한 오랄 케어 제품을 만듭니다. 닥터노아 제품은 자연을 닮아 아름답고, 자연의 솜씨를 익혀 제 기능을 하기에도 충분합니다.',
        logoUrl:
          'https://pillykr.s3.ap-northeast-2.amazonaws.com/store/brand/drnoah/logo.png',
        coverUrl:
          'https://pillykr.s3.ap-northeast-2.amazonaws.com/store/brand/drnoah/brand.jpg',
        modTsp: '2022-11-01 02:50:25',
        regTsp: '2022-11-01 02:50:25',
      },
      certs: null,
      faqs: null,
      noticeInfo: null,
      thumbnailImages: [
        {
          type: 'THUMBNAIL',
          ord: 1.0,
          url: 'https://img.pilly.kr/product/store/PDBUVVOI3999/product_01.png',
          modTsp: '2022-11-01 02:51:12',
          regTsp: '2022-11-01 02:51:12',
        },
        {
          type: 'THUMBNAIL',
          ord: 2.0,
          url: 'https://img.pilly.kr/product/store/PDBUVVOI3999/product_02.jpg',
          modTsp: '2022-11-01 02:51:12',
          regTsp: '2022-11-01 02:51:12',
        },
        {
          type: 'THUMBNAIL',
          ord: 3.0,
          url: 'https://img.pilly.kr/product/store/PDBUVVOI3999/product_03.jpg',
          modTsp: '2022-11-01 02:51:12',
          regTsp: '2022-11-01 02:51:12',
        },
        {
          type: 'THUMBNAIL',
          ord: 4.0,
          url: 'https://img.pilly.kr/product/store/PDBUVVOI3999/product_04.jpg',
          modTsp: '2022-11-01 02:51:12',
          regTsp: '2022-11-01 02:51:12',
        },
        {
          type: 'THUMBNAIL',
          ord: 5.0,
          url: 'https://img.pilly.kr/product/store/PDBUVVOI3999/product_05.jpg',
          modTsp: '2022-11-01 02:51:12',
          regTsp: '2022-11-01 02:51:12',
        },
      ],
      detailImages: null,
      reviewRating: 0.0,
      reviewCount: 0.0,
      reviewStats: null,
      modTsp: '2022-10-19 21:30:47',
      regTsp: '2022-10-19 21:30:47',
    },
    {
      code: 'PDHVICPP3333',
      nick: 'o-bits-xylitol-toothpaste-yuja',
      type: 'EXTRA',
      brand: null,
      title: '오비츠 자일리톨 고체치약 유자민트향',
      subTitle: null,
      price: 5300.0,
      listPrice: null,
      count: null,
      applyCount: null,
      surveyId: null,
      checkState: null,
      imageUrl: null,
      conceptUrl: null,
      bottleUrl: null,
      color: '#cccccc',
      summary: null,
      content: null,
      volume: null,
      intake: null,
      shape: null,
      slogan: null,
      description: null,
      ingredients: null,
      caution: null,
      iconText: null,
      limitation: null,
      saleState: 1.0,
      onetimeState: null,
      subscriberState: null,
      eventState: null,
      soldoutState: null,
      takebackCount: null,
      ord: null,
      maxPurchaseLimit: 5.0,
      discount: null,
      hashtag: null,
      seoTitle: null,
      seoKeywords: null,
      surveySummary: null,
      medicineNo: '202210270060',
      medicineTitle: null,
      medicineImageUrl: null,
      distributionTitle: null,
      tags: null,
      contains: null,
      marks: null,
      topCategoryCode: 'health_supplies',
      topCategoryTitle: '건강용품',
      brandInfo: {
        nickname: 'drnoah',
        title: '닥터노아',
        slogan:
          '매일 쓰는 칫솔과 치약에서 영원히 썩지 않는 것들을 덜어내고, 자연에서 얻은 재료와 성분을 더해 우리 몸에 안전하고 건강한 오랄 케어 제품을 만듭니다. 닥터노아 제품은 자연을 닮아 아름답고, 자연의 솜씨를 익혀 제 기능을 하기에도 충분합니다.',
        logoUrl:
          'https://pillykr.s3.ap-northeast-2.amazonaws.com/store/brand/drnoah/logo.png',
        coverUrl:
          'https://pillykr.s3.ap-northeast-2.amazonaws.com/store/brand/drnoah/brand.jpg',
        modTsp: '2022-11-01 02:50:25',
        regTsp: '2022-11-01 02:50:25',
      },
      certs: null,
      faqs: null,
      noticeInfo: null,
      thumbnailImages: [
        {
          type: 'THUMBNAIL',
          ord: 1.0,
          url: 'https://img.pilly.kr/product/store/PDHVICPP3333/product_01.png',
          modTsp: '2022-11-01 02:51:12',
          regTsp: '2022-11-01 02:51:12',
        },
        {
          type: 'THUMBNAIL',
          ord: 2.0,
          url: 'https://img.pilly.kr/product/store/PDHVICPP3333/product_02.jpg',
          modTsp: '2022-11-01 02:51:12',
          regTsp: '2022-11-01 02:51:12',
        },
        {
          type: 'THUMBNAIL',
          ord: 3.0,
          url: 'https://img.pilly.kr/product/store/PDHVICPP3333/product_03.jpg',
          modTsp: '2022-11-01 02:51:12',
          regTsp: '2022-11-01 02:51:12',
        },
        {
          type: 'THUMBNAIL',
          ord: 4.0,
          url: 'https://img.pilly.kr/product/store/PDHVICPP3333/product_04.jpg',
          modTsp: '2022-11-01 02:51:12',
          regTsp: '2022-11-01 02:51:12',
        },
        {
          type: 'THUMBNAIL',
          ord: 5.0,
          url: 'https://img.pilly.kr/product/store/PDHVICPP3333/product_05.jpg',
          modTsp: '2022-11-01 02:51:12',
          regTsp: '2022-11-01 02:51:12',
        },
      ],
      detailImages: null,
      reviewRating: 0.0,
      reviewCount: 0.0,
      reviewStats: null,
      modTsp: '2022-10-19 21:30:47',
      regTsp: '2022-10-19 21:30:47',
    },
    {
      code: 'PDCUSGCT6339',
      nick: 'therabreath-oralrinse-icymint',
      type: 'EXTRA',
      brand: null,
      title: '프레시브레스 오랄린스 아이시민트 473ML',
      subTitle: null,
      price: 10300.0,
      listPrice: 15000.0,
      count: null,
      applyCount: null,
      surveyId: null,
      checkState: null,
      imageUrl: null,
      conceptUrl: null,
      bottleUrl: null,
      color: '#cccccc',
      summary:
        '- 구강내 프라그 및 악취 제거\n- 무알콜&무색소&무인공향료\n- 순하면서도 시원하고 청량한 가글',
      content: null,
      volume: null,
      intake: null,
      shape: null,
      slogan: '우리 가족 덴탈케어를 위한',
      description: null,
      ingredients: null,
      caution: null,
      iconText: 'therabreath-oralicy',
      limitation: null,
      saleState: 1.0,
      onetimeState: null,
      subscriberState: null,
      eventState: null,
      soldoutState: null,
      takebackCount: null,
      ord: null,
      maxPurchaseLimit: 5.0,
      discount: '31%',
      hashtag: null,
      seoTitle: null,
      seoKeywords: null,
      surveySummary: null,
      medicineNo: '202206211402',
      medicineTitle: null,
      medicineImageUrl: null,
      distributionTitle: null,
      tags: null,
      contains: null,
      marks: null,
      topCategoryCode: 'health_supplies',
      topCategoryTitle: '건강용품',
      brandInfo: {
        nickname: 'therabreath',
        title: '테라브레스',
        slogan:
          '마르지 않는 상쾌함! 미국의 치과의사 아버지가 입냄새나는 딸을 위해 만든 덴탈케어 브랜드 테라브레스입니다. 무알콜, 무색소, 무인공향료로 순한 사용감과 강력한 구취제거 효과를 제공합니다.',
        logoUrl:
          'https://pillykr.s3.ap-northeast-2.amazonaws.com/store/brand/therabreath/logo.png',
        coverUrl:
          'https://pillykr.s3.ap-northeast-2.amazonaws.com/store/brand/therabreath/brand.jpg',
        modTsp: '2022-11-01 02:50:25',
        regTsp: '2022-11-01 02:50:25',
      },
      certs: null,
      faqs: null,
      noticeInfo: null,
      thumbnailImages: [
        {
          type: 'THUMBNAIL',
          ord: 1.0,
          url: 'https://img.pilly.kr/product/store/PDCUSGCT6339/product_01.png',
          modTsp: '2022-11-01 02:51:10',
          regTsp: '2022-11-01 02:51:10',
        },
        {
          type: 'THUMBNAIL',
          ord: 2.0,
          url: 'https://img.pilly.kr/product/store/PDCUSGCT6339/product_02.jpg',
          modTsp: '2022-11-01 02:51:10',
          regTsp: '2022-11-01 02:51:10',
        },
      ],
      detailImages: null,
      reviewRating: 0.0,
      reviewCount: 0.0,
      reviewStats: null,
      modTsp: '2022-06-08 15:36:58',
      regTsp: '2022-06-08 15:36:58',
    },
    {
      code: 'PDQEXZEZ4933',
      nick: 'therabreath-oralrinse-mildmint',
      type: 'EXTRA',
      brand: null,
      title: '프레시브레스 오랄린스 마일드민트 473ML',
      subTitle: null,
      price: 10300.0,
      listPrice: 15000.0,
      count: null,
      applyCount: null,
      surveyId: null,
      checkState: null,
      imageUrl: null,
      conceptUrl: null,
      bottleUrl: null,
      color: '#cccccc',
      summary:
        '- 구강내 프라그 및 악취 제거\n- 무알콜&무색소&무인공향료\n- 자극이 적고 순하고 부드러운 가글',
      content: null,
      volume: null,
      intake: null,
      shape: null,
      slogan: '우리 가족 덴탈케어를 위한',
      description: null,
      ingredients: null,
      caution: null,
      iconText: 'therabreath-oralmild',
      limitation: null,
      saleState: 1.0,
      onetimeState: null,
      subscriberState: null,
      eventState: null,
      soldoutState: null,
      takebackCount: null,
      ord: null,
      maxPurchaseLimit: 5.0,
      discount: '31%',
      hashtag: null,
      seoTitle: null,
      seoKeywords: null,
      surveySummary: null,
      medicineNo: '202206211401',
      medicineTitle: null,
      medicineImageUrl: null,
      distributionTitle: null,
      tags: null,
      contains: null,
      marks: null,
      topCategoryCode: 'health_supplies',
      topCategoryTitle: '건강용품',
      brandInfo: {
        nickname: 'therabreath',
        title: '테라브레스',
        slogan:
          '마르지 않는 상쾌함! 미국의 치과의사 아버지가 입냄새나는 딸을 위해 만든 덴탈케어 브랜드 테라브레스입니다. 무알콜, 무색소, 무인공향료로 순한 사용감과 강력한 구취제거 효과를 제공합니다.',
        logoUrl:
          'https://pillykr.s3.ap-northeast-2.amazonaws.com/store/brand/therabreath/logo.png',
        coverUrl:
          'https://pillykr.s3.ap-northeast-2.amazonaws.com/store/brand/therabreath/brand.jpg',
        modTsp: '2022-11-01 02:50:25',
        regTsp: '2022-11-01 02:50:25',
      },
      certs: null,
      faqs: null,
      noticeInfo: null,
      thumbnailImages: [
        {
          type: 'THUMBNAIL',
          ord: 1.0,
          url: 'https://img.pilly.kr/product/store/PDQEXZEZ4933/product_01.png',
          modTsp: '2022-11-01 02:51:10',
          regTsp: '2022-11-01 02:51:10',
        },
        {
          type: 'THUMBNAIL',
          ord: 2.0,
          url: 'https://img.pilly.kr/product/store/PDQEXZEZ4933/product_02.jpg',
          modTsp: '2022-11-01 02:51:10',
          regTsp: '2022-11-01 02:51:10',
        },
      ],
      detailImages: null,
      reviewRating: 0.0,
      reviewCount: 0.0,
      reviewStats: null,
      modTsp: '2022-06-08 15:36:53',
      regTsp: '2022-06-08 15:36:53',
    },
  ],
};

export { data };
